language: php

php:
  - 7.3

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update

before_script:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - vendor/bin/tester -s -p php -c ./tests/php.ini-unix tests

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
